# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('Profile_photo', models.ImageField(blank=True, upload_to='images/')),
                ('Bio', models.TextField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grocery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grocery', to='fridge.Grocery')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pub_date',
            new_name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
