# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_auto_20181101_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='cart',
            name='paid',
            field=models.CharField(default='False', max_length=20),
        ),
    ]
