# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_auto_20181101_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_ordered',
        ),
    ]
