# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_remove_cart_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='fridge.Grocery'),
        ),
    ]
